### PR TITLE
Initialize Events project

### PR DESCRIPTION
**Pull request by mbaechler**
```
This project uses gradle as a build tool, java 8 as language level
and assertj + junit for testing.
```

The gradle part may be wrong, it's the first time I use it.
Every choices are subject to discussion, feel free to comment/ask.

### CODE REVIEW

**Comment by nicolaspayot** [comment]
Where could we add the front-end app? As all files related to the java app seems to be in the root directory.

**Comment by mbaechler** [comment]
good question. I'll answer with another one : do we want a frontend by domain or can we just go with a single frontend for all ?

**Comment by nicolaspayot** [comment]
Another key point I was wondering about. I'd say one by domain as it can allow developers to choose different technologies but I also think that the view layer should be consistent between domains / contexts (issue #8).

**Comment by jeantil** [comment]
This point can easily be solved by a refactoring once a consensus has been reached. In the meantime this PR LGTM.

**Comment by aminx4** [comment]
LGTM.

**Comment by rnowif** [comment]
LGTM

**Comment by bravogolfgolf** [comment]
LGTM

**Comment by thebignet** [comment]
LGTM

**Comment by nphumbert** [comment]
LGTM

**Pull request merged**
