### PR TITLE
Set Events project name to "events"

### PR DESCRIPTION
**Pull request by thebignet**
I added a name to Gradle project Events.

### CODE REVIEW

**Comment by ldez** [comment]
LGTM

**Comment by mbaechler** [comment]
:+1:

**Comment by rnowif** [comment]
LGTM

**Comment by thebignet** [comment]
Can someone with merge rights merge this PR ?

**Comment by aminx4** [comment]
LGTM

**Comment by bravogolfgolf** [comment]
LGTM

**Pull request merged**
